
import './administration/dependencies/dependencies-manager'
import './administration/affiliations/affiliations-manager'
import './administration/campuses/campuses-manager'
import './administration/participant-types/participant-types-manager'
import './administration/programs/programs-manager'
import './administration/areas/areas-manager'
import './administration/formats/formats-manager'
import './administration/organizations/organizations-manager'
import './components/searchable-select'
import './components/command-palette'
import './scroll-activity'
import './handle-sidebar'
import './copy-link-events'
import './events/events-create'
import './users/users-index'
// import './calendar/index'
