
import './administration/dependencies/dependencies-manager'
import './administration/affiliations/affiliations-manager'
import './administration/participant-types/participant-types-manager'
import './administration/areas/areas-manager'
import './administration/formats/formats-manager'
import './handle-sidebar'
import './copy-link-events'
import './events/events-create'
import './users/users-index'
// import './calendar/index'
