<?php

return [
    'default' => [
        'file' => 'LISTADO_DE_ASISTENCIA_GENERAL_REVISION_9.pdf',
        'startY' => 62.2,
        'rowHeight' => 8.15,
        'maxRows' => 16,
        'header' => [
            'dependency' => ['x' => 78, 'y' => 30.5],
            'area' => ['x' => 128, 'y' => 30.5],
            'title' => ['x' => 44, 'y' => 38.5],
            'date_day' => ['x' => 224, 'y' => 30.5],
            'date_month' => ['x' => 233, 'y' => 30.5],
            'date_year' => ['x' => 245.5, 'y' => 30.5],
        ],
        'columns' => [
            'number' => ['x' => 19, 'w' => 12, 'align' => 'C'],
            'name' => ['x' => 30.2, 'w' => 61, 'align' => 'L', 'limit' => 32],
            'role' => ['x' => 105.5, 'w' => 28, 'align' => 'L', 'limit' => 13],
            'program' => [
                'x' => 137.3,
                'w' => 34,
                'align' => 'L',
                'limit' => 25,
                'fontSize' => 10,
            ],
            'email' => ['x' => 180, 'w' => 34, 'align' => 'L', 'limit' => 30],
            'time' => ['x' => 242.2, 'w' => 20, 'align' => 'C'],
        ],
        'date_format' => ['day' => 'd', 'month' => 'm', 'year' => 'Y'],
        'time_format' => 'h:i A',
    ],
    'general' => [
        'file' => 'LISTADO_DE_ASISTENCIA_GENERAL_REVISION_9.pdf',
        'startY' => 62.2,
        'rowHeight' => 8.15,
        'maxRows' => 16,
        'header' => [
            'dependency' => ['x' => 77.91, 'y' => 30.57, 'w' => 123.9, 'limit' => 60],
            'title' => ['x' => 44.1, 'y' => 39.1, 'w' => 218.6, 'limit' => 107],
            'date_day' => ['x' => 223.13, 'y' => 30.87, 'w' => 5.9, 'limit' => 3],
            'date_month' => ['x' => 232.54, 'y' => 30.87, 'w' => 7, 'limit' => 3],
            'date_year' => ['x' => 242.24, 'y' => 30.57, 'w' => 19.6, 'limit' => 9],
        ],
        'columns' => [
            'number' => [
                'x' => 19.11,
                'w' => 12,
                'align' => 'C',
                'h' => 7,
                'limit' => 25,
            ],
            'name' => [
                'x' => 29.69,
                'w' => 74,
                'align' => 'L',
                'h' => 7,
                'limit' => 36,
            ],
            'role' => [
                'x' => 104.66,
                'w' => 32.2,
                'align' => 'L',
                'h' => 7,
                'limit' => 15,
            ],
            'program' => [
                'x' => 137.29,
                'w' => 41.9,
                'align' => 'L',
                'h' => 7,
                'limit' => 24,
                'fontSize' => 10,
            ],
            'email' => [
                'x' => 179.92,
                'w' => 60.8,
                'align' => 'L',
                'h' => 7,
                'limit' => 29,
            ],
            'time' => [
                'x' => 242.24,
                'w' => 20,
                'align' => 'C',
                'h' => 7,
                'limit' => 25,
            ],
        ],
        'date_format' => ['day' => 'd', 'month' => 'm', 'year' => 'Y'],
        'time_format' => 'h:i A',
    ],
    'bienestar' => [
        'file' => 'LISTADO_DE_ASISTENCIA_BIENESTAR_REVISION_6.pdf',
        'startY' => 80,
        'rowHeight' => 9.15,
        'maxRows' => 12,
        'header' => [
            'dependency' => ['x' => 77.91, 'y' => 27.93, 'w' => 124, 'limit' => 60],
            'area' => ['x' => 53.5, 'y' => 35.87, 'w' => 43.7, 'limit' => 21],
            'title' => ['x' => 139.94, 'y' => 35.87, 'w' => 83.3, 'limit' => 40],
            'date_day' => ['x' => 237.54, 'y' => 27.93, 'w' => 40, 'limit' => 19],
            'date_month' => ['x' => 274.58, 'y' => 27.93, 'w' => 40, 'limit' => 19],
            'date_year' => ['x' => 317.5, 'y' => 27.93, 'w' => 40, 'limit' => 19],
            'responsible' => ['x' => 261.94, 'y' => 35.87, 'w' => 77.4, 'limit' => 37],
        ],
        'columns' => [
            'name' => [
                'x' => 29.99,
                'w' => 67.4,
                'align' => 'L',
                'h' => 7,
                'limit' => 33,
            ],
            'identification' => [
                'x' => 99.07,
                'w' => 42.4,
                'align' => 'L',
                'h' => 7,
                'limit' => 20,
            ],
            'role' => [
                'x' => 142.88,
                'w' => 38,
                'align' => 'L',
                'h' => 7,
                'limit' => 18,
            ],
            'program' => [
                'x' => 182.86,
                'w' => 73.6,
                'align' => 'L',
                'h' => 7,
                'limit' => 36,
            ],
            'gender' => [
                'Femenino' => ['x' => 259.88, 'y_offset' => 2.65],
                'Masculino' => ['x' => 269.88, 'y_offset' => 2.65],
            ],
            'priority_group' => [
                'Indígena' => ['x' => 280.16, 'y_offset' => 2.65],
                'Afrodescendiente' => ['x' => 290.16, 'y_offset' => 2.65],
                'Discapacitado' => ['x' => 299.57, 'y_offset' => 2.65],
                'Víctima de Conflicto Armado' => ['x' => 310.15, 'y_offset' => 2.35],
                'Comunidad LGTBQ+' => ['x' => 319.85, 'y_offset' => 2.65],
                'Habitante de Frontera' => ['x' => 331.32, 'y_offset' => 2.65],
            ],
        ],
        'date_format' => ['day' => 'd', 'month' => 'F', 'year' => 'Y'],
        'time_format' => 'H:i',
    ],
    'proyeccion_social' => [
        'file' => 'LISTADO_DE_ASISTENCIA_PROYECCION_SOCIAL_REVISION_5.pdf',
        'startY' => 62,
        'rowHeight' => 7,
        'maxRows' => 16,
        'header' => [
            'title' => ['x' => 174.92, 'y' => 32.63, 'w' => 164.7, 'limit' => 80],
            'date_day' => ['x' => 86.43, 'y' => 31.46, 'w' => 5.9, 'limit' => 3],
            'date_month' => ['x' => 98.78, 'y' => 31.46, 'w' => 13.3, 'limit' => 6],
            'date_year' => ['x' => 113.18, 'y' => 31.16, 'w' => 13.3, 'limit' => 6],
        ],
        'columns' => [
            'name' => [
                'x' => 47.04,
                'w' => 50.4,
                'align' => 'L',
                'h' => 7,
                'limit' => 29,
                'fontSize' => 10,
            ],
            'identification' => [
                'x' => 111.13,
                'w' => 31.5,
                'align' => 'L',
                'h' => 7,
                'limit' => 15,
            ],
            'email' => [
                'x' => 198.73,
                'w' => 31,
                'align' => 'L',
                'h' => 7,
                'limit' => 20,
                'fontSize' => 9,
            ],
            'program' => [
                'x' => 229.31,
                'w' => 45.7,
                'align' => 'L',
                'h' => 7,
                'limit' => 29,
                'fontSize' => 9,
            ],
            'address' => [
                'x' => 143.17,
                'w' => 31,
                'align' => 'L',
                'h' => 7,
                'limit' => 16,
                'fontSize' => 11,
            ],
            'phone' => [
                'x' => 173.45,
                'w' => 25,
                'align' => 'L',
                'h' => 7,
                'limit' => 15,
            ],
            'role' => [
                'Docente' => ['x' => 278.69, 'y_offset' => 1.76],
                'Estudiante' => ['x' => 302.51, 'y_offset' => 2.35],
                'Graduado' => ['x' => 313.97, 'y_offset' => 2.06],
                'Comunidad Externa' => ['x' => 328.38, 'y_offset' => 1.76],
                'Administrativos' => ['x' => 291.04, 'y_offset' => 2.06],
            ],
            'gender' => [
                'Femenino' => ['x' => 104.36, 'y_offset' => 1.76],
                'Masculino' => ['x' => 97.9, 'y_offset' => 1.47],
            ],
        ],
        'date_format' => ['day' => 'd', 'month' => 'F', 'year' => 'Y'],
        'time_format' => 'H:i',
    ],
    'capacitacion_externa' => [
        'file' => 'LISTADO_DE_ASISTENCIA_CAPACITACION_EXTERNA_PROYECCION_SOCIAL_REVISION_7.pdf',
        'startY' => 48.5,
        'rowHeight' => 5.05,
        'maxRows' => 26,
        'header' => [
            'title' => ['x' => 59.97, 'y' => 31.46, 'w' => 85.2, 'limit' => 41],
            'date_day' => [
                'x' => 161.1,
                'y' => 31.75,
                'fontSize' => 10,
                'w' => 5.9,
                'limit' => 3,
                'align' => 'C',
            ],
            'date_month' => [
                'x' => 171.1,
                'y' => 31.75,
                'fontSize' => 10,
                'w' => 11.1,
                'limit' => 6,
                'align' => 'C',
            ],
            'date_year' => [
                'x' => 181.68,
                'y' => 32.04,
                'fontSize' => 10,
                'w' => 11.7,
                'limit' => 6,
                'align' => 'C',
            ],
        ],
        'columns' => [
            'number' => [
                'x' => 19.4,
                'w' => 5.9,
                'align' => 'C',
                'h' => 7,
                'limit' => 3,
                'fontSize' => 10,
            ],
            'name' => [
                'x' => 26.75,
                'w' => 62.5,
                'align' => 'L',
                'h' => 7,
                'limit' => 36,
                'fontSize' => 10,
            ],
            'email' => [
                'x' => 139.94,
                'w' => 54.3,
                'align' => 'L',
                'h' => 7,
                'limit' => 35,
                'fontSize' => 9,
            ],
            'role' => [
                'x' => 195.2,
                'w' => 27.8,
                'align' => 'L',
                'h' => 7,
                'limit' => 16,
                'fontSize' => 10,
            ],
            'time' => [
                'x' => 236.07,
                'w' => 20,
                'align' => 'C',
                'h' => 7,
                'limit' => 25,
                'fontSize' => 10,
            ],
            'phone' => [
                'x' => 89.66,
                'w' => 49.3,
                'align' => 'L',
                'h' => 7,
                'limit' => 28,
                'fontSize' => 10,
            ],
        ],
        'date_format' => ['day' => 'd', 'month' => 'F', 'year' => 'Y'],
        'time_format' => 'h:i A',
    ],
];
