<?php

return [
    'default' => [
        'file' => 'LISTADO_DE_ASISTENCIA_GENERAL_REVISION_9.pdf',
        'startY' => 62.2,
        'rowHeight' => 8.15,
        'maxRows' => 16,
        'header' => [
            'dependency' => ['x' => 78, 'y' => 30.5],
            'area' => ['x' => 128, 'y' => 30.5],
            'title' => ['x' => 44, 'y' => 38.5],
            'date_day' => ['x' => 224, 'y' => 30.5],
            'date_month' => ['x' => 233, 'y' => 30.5],
            'date_year' => ['x' => 245.5, 'y' => 30.5],
        ],
        'columns' => [
            'number' => ['x' => 19, 'w' => 12, 'align' => 'C'],
            'name' => ['x' => 30.2, 'w' => 61, 'align' => 'L', 'limit' => 32],
            'role' => ['x' => 105.5, 'w' => 28, 'align' => 'L', 'limit' => 13],
            'program' => [
                'x' => 137.3,
                'w' => 34,
                'align' => 'L',
                'limit' => 25,
                'fontSize' => 10,
            ],
            'email' => ['x' => 180, 'w' => 34, 'align' => 'L', 'limit' => 30],
            'time' => ['x' => 242.2, 'w' => 20, 'align' => 'C'],
        ],
        'date_format' => ['day' => 'd', 'month' => 'm', 'year' => 'Y'],
        'time_format' => 'h:i A',
    ],
    'general' => [
        'file' => 'general_1777609692.pdf',
        'startY' => 60.2,
        'rowHeight' => 8.15,
        'maxRows' => 16,
        'header' => [
            'title' => ['x' => 43.8, 'y' => 39.39, 'w' => 218.6, 'limit' => 107],
            'date_day' => [
                'x' => 222.25,
                'y' => 30.87,
                'w' => 5.9,
                'limit' => 3,
                'align' => 'C',
            ],
            'date_year' => [
                'x' => 241.65,
                'y' => 30.87,
                'w' => 19.6,
                'limit' => 9,
                'align' => 'C',
            ],
            'date_month' => [
                'x' => 231.07,
                'y' => 30.87,
                'w' => 7,
                'limit' => 3,
                'align' => 'C',
            ],
            'dependency' => ['x' => 77.61, 'y' => 30.86, 'w' => 123.9, 'limit' => 60],
        ],
        'columns' => [
            'name' => [
                'x' => 30.57,
                'w' => 74,
                'align' => 'L',
                'h' => 7,
                'limit' => 36,
            ],
            'role' => [
                'x' => 104.95,
                'w' => 32.2,
                'align' => 'L',
                'h' => 7,
                'limit' => 15,
            ],
            'time' => [
                'x' => 241.06,
                'w' => 20,
                'align' => 'C',
                'h' => 7,
                'limit' => 25,
            ],
            'email' => [
                'x' => 181.39,
                'w' => 60.8,
                'align' => 'L',
                'h' => 7,
                'limit' => 29,
            ],
            'number' => [
                'x' => 20.58,
                'w' => 8.4,
                'align' => 'C',
                'h' => 7,
                'limit' => 4,
            ],
            'program' => [
                'x' => 137.88,
                'w' => 41.1,
                'align' => 'L',
                'h' => 7,
                'limit' => 24,
                'fontSize' => 10,
            ],
        ],
        'date_format' => ['day' => 'd', 'year' => 'Y', 'month' => 'm'],
        'time_format' => 'h:i A',
    ],
    'bienestar' => [
        'file' => 'bienestar_1777609705.pdf',
        'startY' => 79,
        'rowHeight' => 9.15,
        'maxRows' => 12,
        'header' => [
            'area' => ['x' => 53.5, 'y' => 35.87, 'w' => 43.7, 'limit' => 21],
            'title' => ['x' => 139.94, 'y' => 35.87, 'w' => 83.3, 'limit' => 40],
            'date_day' => [
                'x' => 233.42,
                'y' => 28.22,
                'w' => 5.9,
                'limit' => 3,
                'align' => 'C',
            ],
            'date_year' => [
                'x' => 313.68,
                'y' => 28.52,
                'w' => 16.5,
                'limit' => 8,
                'align' => 'C',
            ],
            'date_month' => [
                'x' => 267.23,
                'y' => 28.22,
                'w' => 27.1,
                'limit' => 13,
                'align' => 'C',
            ],
            'dependency' => ['x' => 77.91, 'y' => 27.93, 'w' => 124, 'limit' => 60],
            'responsible' => ['x' => 261.94, 'y' => 35.87, 'w' => 77.4, 'limit' => 37],
        ],
        'columns' => [
            'name' => [
                'x' => 29.99,
                'w' => 67.4,
                'align' => 'L',
                'h' => 7,
                'limit' => 33,
            ],
            'role' => [
                'x' => 142.88,
                'w' => 38,
                'align' => 'L',
                'h' => 7,
                'limit' => 18,
            ],
            'program' => [
                'x' => 182.86,
                'w' => 73.6,
                'align' => 'L',
                'h' => 7,
                'limit' => 36,
            ],
            'identification' => [
                'x' => 99.07,
                'w' => 42.4,
                'align' => 'L',
                'h' => 7,
                'limit' => 20,
            ],
            'gender' => [
                'fontSize' => 12,
                'Femenino' => ['x' => 259.88, 'y_offset' => 3.53],
                'Masculino' => ['x' => 269.88, 'y_offset' => 3.53],
            ],
            'priority_group' => [
                'fontSize' => 12,
                'Indígena' => ['x' => 280.16, 'y_offset' => 3.53],
                'Discapacitado' => ['x' => 299.57, 'y_offset' => 3.53],
                'Afrodescendiente' => ['x' => 290.16, 'y_offset' => 3.53],
                'Comunidad LGTBQ+' => ['x' => 319.85, 'y_offset' => 3.53],
                'Habitante de Frontera' => ['x' => 331.32, 'y_offset' => 3.53],
                'Víctima de Conflicto Armado' => ['x' => 310.15, 'y_offset' => 3.23],
            ],
        ],
        'date_format' => ['day' => 'd', 'year' => 'Y', 'month' => 'F'],
        'time_format' => 'H:i',
    ],
    'proyeccion_social' => [
        'file' => 'proyeccion_social_1777608963.pdf',
        'startY' => 77.9,
        'rowHeight' => 7,
        'maxRows' => 16,
        'header' => [
            'title' => ['x' => 181.39, 'y' => 29.1, 'w' => 164.7, 'limit' => 80],
            'date_day' => ['x' => 86.43, 'y' => 31.46, 'w' => 5.9, 'limit' => 3],
            'date_year' => ['x' => 113.18, 'y' => 31.16, 'w' => 13.3, 'limit' => 6],
            'date_month' => ['x' => 98.78, 'y' => 31.46, 'w' => 13.3, 'limit' => 6],
        ],
        'columns' => [
            'name' => [
                'x' => 49.68,
                'w' => 45.3,
                'align' => 'L',
                'h' => 7,
                'limit' => 26,
                'fontSize' => 10,
            ],
            'email' => [
                'x' => 197.26,
                'w' => 39.8,
                'align' => 'L',
                'h' => 7,
                'limit' => 26,
                'fontSize' => 9,
            ],
            'phone' => [
                'x' => 168.16,
                'w' => 28.9,
                'align' => 'L',
                'h' => 7,
                'limit' => 14,
            ],
            'address' => [
                'x' => 140.52,
                'w' => 27.1,
                'align' => 'L',
                'h' => 7,
                'limit' => 14,
                'fontSize' => 11,
            ],
            'program' => [
                'x' => 237.54,
                'w' => 45.7,
                'align' => 'L',
                'h' => 7,
                'limit' => 29,
                'fontSize' => 9,
            ],
            'identification' => [
                'x' => 108.48,
                'w' => 31.5,
                'align' => 'L',
                'h' => 7,
                'limit' => 15,
            ],
            'role' => [
                'fontSize' => 12,
                'Docente' => ['x' => 286.34, 'y_offset' => 1.47],
                'Graduado' => ['x' => 312.5, 'y_offset' => 1.47],
                'Estudiante' => ['x' => 302.8, 'y_offset' => 1.76],
                'Administrativos' => ['x' => 294.28, 'y_offset' => 1.47],
                'Comunidad Externa' => ['x' => 326.91, 'y_offset' => 1.76],
            ],
            'gender' => [
                'fontSize' => 12,
                'Femenino' => ['x' => 102.01, 'y_offset' => 1.18],
                'Masculino' => ['x' => 94.96, 'y_offset' => 1.47],
            ],
        ],
        'date_format' => ['day' => 'd', 'year' => 'Y', 'month' => 'F'],
        'time_format' => 'H:i',
    ],
    'capacitacion_externa' => [
        'file' => 'capacitacion_externa_1777608969.pdf',
        'startY' => 48.5,
        'rowHeight' => 5.05,
        'maxRows' => 26,
        'header' => [
            'title' => ['x' => 59.97, 'y' => 31.46, 'w' => 85.2, 'limit' => 41],
            'date_day' => [
                'x' => 161.1,
                'y' => 31.75,
                'fontSize' => 10,
                'w' => 5.9,
                'limit' => 3,
                'align' => 'C',
            ],
            'date_year' => [
                'x' => 181.97,
                'y' => 31.75,
                'fontSize' => 10,
                'w' => 11.7,
                'limit' => 6,
                'align' => 'C',
            ],
            'date_month' => [
                'x' => 171.1,
                'y' => 31.75,
                'fontSize' => 10,
                'w' => 11.1,
                'limit' => 6,
                'align' => 'C',
            ],
        ],
        'columns' => [
            'name' => [
                'x' => 26.75,
                'w' => 62.5,
                'align' => 'L',
                'h' => 7,
                'limit' => 36,
                'fontSize' => 10,
            ],
            'role' => [
                'x' => 195.2,
                'w' => 27.8,
                'align' => 'L',
                'h' => 7,
                'limit' => 16,
                'fontSize' => 10,
            ],
            'time' => [
                'x' => 236.07,
                'w' => 20,
                'align' => 'C',
                'h' => 7,
                'limit' => 25,
                'fontSize' => 10,
            ],
            'email' => [
                'x' => 139.94,
                'w' => 54.3,
                'align' => 'L',
                'h' => 7,
                'limit' => 35,
                'fontSize' => 9,
            ],
            'phone' => [
                'x' => 89.66,
                'w' => 49.3,
                'align' => 'L',
                'h' => 7,
                'limit' => 28,
                'fontSize' => 10,
            ],
            'number' => [
                'x' => 19.4,
                'w' => 5.9,
                'align' => 'C',
                'h' => 7,
                'limit' => 3,
                'fontSize' => 10,
            ],
        ],
        'date_format' => ['day' => 'd', 'year' => 'Y', 'month' => 'F'],
        'time_format' => 'h:i A',
    ],
];
